config/routes.rb
Rails.application.routes.draw do
  resources :ponies
  resources :stables

end

app/models/pony.rb
class Pony < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	belongs_to :stable
end

app/models/stable.rb
class Stable < ActiveRecord::Base
	has_many :ponies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: [:show, :edit, :update, :destroy]

  # GET /ponies
  # GET /ponies.json
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1
  # GET /ponies/1.json
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies
  # POST /ponies.json
  def create
    @pony = Pony.new(pony_params)

    respond_to do |format|
      if @pony.save
        format.html { redirect_to @pony, notice: 'Pony was successfully created.' }
        format.json { render :show, status: :created, location: @pony }
      else
        format.html { render :new }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponies/1
  # PATCH/PUT /ponies/1.json
  def update
    respond_to do |format|
      if @pony.update(pony_params)
        format.html { redirect_to @pony, notice: 'Pony was successfully updated.' }
        format.json { render :show, status: :ok, location: @pony }
      else
        format.html { render :edit }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponies/1
  # DELETE /ponies/1.json
  def destroy
    @pony.destroy
    respond_to do |format|
      format.html { redirect_to ponies_url, notice: 'Pony was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pony_params
      params.require(:pony).permit(:name, :age, :height, :colour, :rate, :picture)
    end
end

app/controllers/stables_controller.rb
class StablesController < ApplicationController
  before_action :set_stable, only: [:show, :edit, :update, :destroy]

  # GET /stables
  # GET /stables.json
  def index
    @stables = Stable.all
  end

  # GET /stables/1
  # GET /stables/1.json
  def show
  end

  # GET /stables/new
  def new
    @stable = Stable.new
  end

  # GET /stables/1/edit
  def edit
  end

  # POST /stables
  # POST /stables.json
  def create
    @stable = Stable.new(stable_params)

    respond_to do |format|
      if @stable.save
        format.html { redirect_to @stable, notice: 'Stable was successfully created.' }
        format.json { render :show, status: :created, location: @stable }
      else
        format.html { render :new }
        format.json { render json: @stable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stables/1
  # PATCH/PUT /stables/1.json
  def update
    respond_to do |format|
      if @stable.update(stable_params)
        format.html { redirect_to @stable, notice: 'Stable was successfully updated.' }
        format.json { render :show, status: :ok, location: @stable }
      else
        format.html { render :edit }
        format.json { render json: @stable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stables/1
  # DELETE /stables/1.json
  def destroy
    @stable.destroy
    respond_to do |format|
      format.html { redirect_to stables_url, notice: 'Stable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stable
      @stable = Stable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stable_params
      params.require(:stable).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/helpers/stables_helper.rb
module StablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bojoponies</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">BoJoPonies</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ponies">Ponies</a></li>
        <li class="active"><a href="/stables">Stables</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2015
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</body>
</html>

app/views/ponies/_form.html.erb
<%= form_for(@pony) do |f| %>
  <% if @pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% @pony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ponies/edit.html.erb
<h1>Editing Pony</h1>

<%= render 'form' %>

<%= link_to 'Show', @pony %> |
<%= link_to 'Back', ponies_path %>

app/views/ponies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ponies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Height</th>
      <th>Colour</th>
      <th>Rate</th>
      <th>Picture</th>
      <th>Stable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name %></td>
        <td><%= pony.age %></td>
        <td><%= pony.height %></td>
        <td><%= pony.colour %></td>
        <td><%= pony.rate %></td>
        <td><%= pony.picture %></td>
        <td><%= pony.stable.name if pony.stable %></td>
        <td><%= link_to 'Show', pony %></td>
        <td><%= link_to 'Edit', edit_pony_path(pony) %></td>
        <td><%= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pony', new_pony_path %>

app/views/ponies/new.html.erb
<h1>New Pony</h1>

<%= render 'form' %>

<%= link_to 'Back', ponies_path %>

app/views/ponies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pony.age %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pony.height %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @pony.colour %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @pony.rate %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@pony.picture_url, :width => 600) if @pony.picture.present? %>
</p>

<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%= link_to 'Back', ponies_path %>

app/views/stables/_form.html.erb
<%= form_for(@stable) do |f| %>
  <% if @stable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stable.errors.count, "error") %> prohibited this stable from being saved:</h2>

      <ul>
      <% @stable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stables/edit.html.erb
<h1>Editing Stable</h1>

<%= render 'form' %>

<%= link_to 'Show', @stable %> |
<%= link_to 'Back', stables_path %>

app/views/stables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stables.each do |stable| %>
      <tr>
        <td><%= stable.name %></td>
        <td><%= stable.location %></td>
        <td><%= link_to 'Show', stable %></td>
        <td><%= link_to 'Edit', edit_stable_path(stable) %></td>
        <td><%= link_to 'Destroy', stable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stable', new_stable_path %>

app/views/stables/new.html.erb
<h1>New Stable</h1>

<%= render 'form' %>

<%= link_to 'Back', stables_path %>

app/views/stables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stable.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @stable.location %>
</p>

<% @stable.ponies.each do |pony| %>

<%= image_tag(pony.picture_url, :width => 600) if pony.picture.present? %>

<% end %>

<%= link_to 'Edit', edit_stable_path(@stable) %> |
<%= link_to 'Back', stables_path %>